name: users-service
namespace: redline
replicas: 1
containerPort: 8000

image:
  repository: 856888988892.dkr.ecr.us-east-1.amazonaws.com/redline/users-service
  tag: latest

# IRSA role ARN from terraform output
irsaRoleArn: "arn:aws:iam::856888988892:role/redline-users-service"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

env:
  - name: DB_SECRET_NAME
    value: "redline/db-credentials"
  - name: AWS_REGION
    value: "us-east-1"
  - name: PORT
    value: "8000"
  - name: COGNITO_USER_POOL_ID
    value: "us-east-1_gWdcBxpaM"
  - name: COGNITO_CLIENT_ID
    value: "7cbn3ild4hjeqna4aipn59qcrm"
  - name: COGNITO_REGION
    value: "us-east-1"

ingress:
  host: "api.redline.fourallthedogs.com"
  pathPrefix: "users"
  certificateArn: "arn:aws:acm:us-east-1:856888988892:certificate/9f63e8e5-4d74-484e-bc37-5754d5628541"
  publicSubnets: "subnet-09108fc1cd192d465,subnet-036e3bb938bfbb308"
  wafAclArn: ""
